import React from 'react';
var SwapQuoteInfo = function (_a) {
    var uniswapDappSharedLogic = _a.uniswapDappSharedLogic, tradeContext = _a.tradeContext;
    return (React.createElement("div", { className: "uni-ic__swap-quote" },
        React.createElement("div", { className: "uni-ic__swap-quote-container" },
            React.createElement("div", { className: "uni-ic__swap-quote-price" },
                React.createElement("div", { color: "text", className: "uni-ic__swap-quote-price-text", style: {
                        padding: '0.1rem 0.5rem 0.1rem 0.35rem',
                        fontSize: '14px',
                    } },
                    React.createElement("span", null,
                        "Best rate on ",
                        tradeContext.uniswapVersion)),
                React.createElement("div", { color: "text", className: "uni-ic__swap-quote-price-text", style: {
                        justifyContent: 'center',
                        alignItems: 'center',
                        display: 'flex',
                        fontSize: '14px',
                    } },
                    React.createElement("span", null,
                        "1 ",
                        tradeContext.fromToken.symbol,
                        " =",
                        ' ',
                        uniswapDappSharedLogic.workOutOneEqualTo(),
                        ' ',
                        tradeContext.toToken.symbol),
                    React.createElement("div", { className: "uni-ic__swap-quote-price-text-info" },
                        React.createElement("div", { style: {
                                padding: '0.25rem',
                                lineHeight: '0',
                                display: 'inline-block',
                            } },
                            React.createElement("svg", { xmlns: "http://www.w3.org/2000/svg", width: "16", height: "16", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" },
                                React.createElement("circle", { cx: "12", cy: "12", r: "10" }),
                                React.createElement("line", { x1: "12", y1: "16", x2: "12", y2: "12" }),
                                React.createElement("line", { x1: "12", y1: "8", x2: "12.01", y2: "8" }))),
                        React.createElement("div", { className: "uni-ic__tooltip-wrapper", style: {
                                right: '10px',
                            } },
                            React.createElement("div", { className: "uni-ic__tooltip-container" },
                                React.createElement("div", { className: "uni-ic__tooltip" },
                                    React.createElement("div", { className: "uni-ic__tooltip__item" },
                                        React.createElement("div", { className: "uni-ic__tooltip__item__title" },
                                            React.createElement("div", { className: "uni-ic__tooltip__item__title__content" }, "Liquidity Provider Fee")),
                                        React.createElement("div", { className: "uni-ic__tooltip__item__value" },
                                            tradeContext.liquidityProviderFee,
                                            ' ',
                                            tradeContext.fromToken.symbol)),
                                    React.createElement("div", { className: "uni-ic__tooltip__item" },
                                        React.createElement("div", { className: "uni-ic__tooltip__item__title" },
                                            React.createElement("div", { className: "uni-ic__tooltip__item__title__content" }, "Route")),
                                        React.createElement("div", { className: "uni-ic__tooltip__item__value" }, tradeContext.routeText)),
                                    tradeContext.minAmountConvertQuote && (React.createElement("div", { className: "uni-ic__tooltip__item" },
                                        React.createElement("div", { className: "uni-ic__tooltip__item__title" },
                                            React.createElement("div", { className: "uni-ic__tooltip__item__title__content" }, "Minimum received")),
                                        React.createElement("div", { className: "uni-ic__tooltip__item__value" },
                                            tradeContext.minAmountConvertQuote,
                                            ' ',
                                            tradeContext.toToken.symbol))),
                                    tradeContext.maximumSent && (React.createElement("div", { className: "uni-ic__tooltip__item" },
                                        React.createElement("div", { className: "uni-ic__tooltip__item__title" },
                                            React.createElement("div", { className: "uni-ic__tooltip__item__title__content" }, "Maximum sent")),
                                        React.createElement("div", { className: "uni-ic__tooltip__item__value" },
                                            tradeContext.maximumSent,
                                            ' ',
                                            tradeContext.fromToken.symbol))),
                                    React.createElement("div", { className: "uni-ic__tooltip__item" },
                                        React.createElement("div", { className: "uni-ic__tooltip__item__title" },
                                            React.createElement("div", { className: "uni-ic__tooltip__item__title__content" }, "Slippage tolerance")),
                                        React.createElement("div", { className: "uni-ic__tooltip__item__value" },
                                            uniswapDappSharedLogic.uniswapPairSettings
                                                .slippage * 100,
                                            "%")))))))))));
};
export default SwapQuoteInfo;
